services:
  - type: worker
    name: crypto-signals-bot
    env: python
    pythonVersion: 3.11.9
    plan: starter

    buildCommand: |
      python -m pip install -U pip setuptools wheel
      pip install --only-binary=:all: numpy==1.26.4 pandas==2.2.3
      pip install -r requirements.txt
      python - << 'PY'
      import sys, ccxt, aiogram
      print("OK build on", sys.version)
      print("ccxt", ccxt.__version__, "aiogram", aiogram.__version__)
      PY

    startCommand: python bot.py

    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TRONGRID_API_KEY
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        value: "-1002800980577"
      - key: ADMIN_USER_IDS
        value: "658712542"
      - key: USDT_TRC20_WALLET
        value: "TJC9gbV1AJ2Y9S8uq8gj1xcd3hs2T53VpD"
      - key: TIMEZONE
        value: "Asia/Riyadh"
      - key: DAILY_REPORT_HOUR_LOCAL
        value: "9"
      - key: MAX_OPEN_TRADES
        value: "8"
      - key: PRICE_2_WEEKS_USD
        value: "30"
      - key: PRICE_4_WEEKS_USD
        value: "60"
      - key: TRIAL_DAYS
        value: "2"
      - key: TRONGRID_BASE
        value: "https://api.trongrid.io"
      - key: USDT_TRC20_CONTRACT
        value: ""
      - key: PIP_PREFER_BINARY
        value: "1"
