# symbols.py — قائمة 70 عملة (يمكن تعديلها)
SYMBOLS = [
    "BTC/USDT","ETH/USDT","BNB/USDT","XRP/USDT","ADA/USDT","SOL/USDT","DOGE/USDT","DOT/USDT","MATIC/USDT","LTC/USDT",
    "LINK/USDT","TRX/USDT","BCH/USDT","UNI/USDT","XLM/USDT","VET/USDT","ICP/USDT","FIL/USDT","AAVE/USDT","SUSHI/USDT",
    "EGLD/USDT","LDO/USDT","GRT/USDT","THETA/USDT","NEAR/USDT","CRO/USDT","CHZ/USDT","ZEC/USDT","BAT/USDT","ENJ/USDT",
    "KSM/USDT","HNT/USDT","CELO/USDT","ROSE/USDT","OCEAN/USDT","KLAY/USDT","RUNE/USDT","AR/USDT","SXP/USDT","QTUM/USDT",
    "ONT/USDT","IOTA/USDT","DCR/USDT","XTZ/USDT","MKR/USDT","SNX/USDT","COMP/USDT","1INCH/USDT","FTM/USDT","HBAR/USDT",
    "WAVES/USDT","ZIL/USDT","XEC/USDT","ANKR/USDT","GALA/USDT","CAKE/USDT","APT/USDT","SAND/USDT","MANA/USDT","MINA/USDT",
    "STX/USDT","FLUX/USDT","RAY/USDT","BLZ/USDT","WOO/USDT","LUNC/USDT","ALGO/USDT","ATOM/USDT","OP/USDT","ARB/USDT"
]
